### PR TITLE
Add multipart support for long sms's 

### PR DESCRIPTION
**Pull request by andreimc**
Previously on long sms over 160 chars it used to throw SmsManager.RESULT_ERROR_GENERIC_FAILURE 

Now you can send super long sms using this library

### CODE REVIEW

**Comment by MBoukhames** [comment]
Need

**Comment by andreimc** [comment]
@geordyvcErasmus is this still maintained ?

**Comment by BCisneros97** [comment]
> @geordyvcErasmus is this still maintained ?

it seems sms_maintained is unmaintained :v

**Comment by andreimc** [comment]
@MBoukhames @BCisneros97 I think I might take over this fork, if you need the multipart SMS stuff you can add:
```  sms_maintained:
    git:
      url: https://github.com/andreimc/flutter_sms.git
```

**Comment by luanSaid** [comment]
man please i need use thissss

**Comment by andreimc** [comment]
@luanSaid 

```
sms_maintained:
    git:
      url: https://github.com/andreimc/flutter_sms.git
```
use this

**Comment by bawantha** [comment]
NEED

**Comment by bawantha** [comment]
is there any flag to use this didn't work for me

**Comment by bawantha** [comment]
SmsManager.RESULT_ERROR_GENERIC_FAILURE

**Comment by bawantha** [comment]
Hey this works perfectly ignore my previous mistakes , Thank you

**Pull request closed without merging**
